[project]
name = "contextual-logger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Terseus", email = "terseus@fastmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
